### ISSUE TITLE
boxquote-describe-function/variable and custom completing-read-functions

### ISSUE THREAD

**Issue by tsdh** [davep/boxquote.el#3]
The functions `boxquote-describe-function` and `boxquote-describe-variable` currently assume that the function or variable being described are the current `car` of `minibuffer-history` (on GNU Emacs).  This assumption has been correct in the past but might not be true anymore.  Concretely, emacs users may use a custom `completing-read-function` (e.g., a home-brewn one, `ido-completing-read` from the builtin ido mode, or `ivy-mode` from https://github.com/abo-abo/swiper), and that doesn't neccessarily need to populate `minibuffer-history`.  FWIW, at least `ivy-mode` does not use `minibuffer-history` and thus the title of a boxquoted variable or function description is always `nil` (or whatever something else has pushed onto `minibuffer-history`; it's at least never the variable or function name).

So it would be great if the assumption that the variable/function name are the first element in some history list could be removed.  I've tested that the `describe-*` functions also return the description as a string (in addition to creating a `*Help*` buffer) in GNU Emacs 22, 24, 25, and XEmacs 21.4.22 and 21.5 beta.  The described variable or function is always the very first word in the string.  The only difference between Emacs and XEmacs is that the latter quotes the function/variable whereas the former doesn't.

I have tested that the following regular expression matches the variable/function name no matter if and how it might be quoted.

``` elisp
(let (l)
  (dolist (desc '("`--th/foo-insert--` is a built-in function in `C source code'."
                  "`--th/foo-insert--' is a built-in function in `C source code'."
                  "‘--th/foo-insert--’ is a built-in function in `C source code'."
                  "--th/foo-insert-- is a built-in function in `C source code'.")
                l)
    (string-match "^[^-/:\\s_\\sw]?\\(\\(?:\\s_\\|\\sw\\|/\\)+\\)[^-/:\\s_\\sw]?" desc)
    (push (match-string 1 desc) l)))
;=> ("--th/foo-insert--" "--th/foo-insert--" "--th/foo-insert--" "--th/foo-insert--")
```

So `string-match` with that regexp could be used instead of relying that the symbol name is the `car` of `minibuffer-history`.  I've tested that with all Emacs and XEmacs versions cited above.  I don't have Emacs 23 handy but I'm very sure that it'll work there, too.

If you think this is the right approach, feel free to request a pull request.

**Comment by davep** [comment]
Having had a bit of time where my concentration wasn't really on emacs stuff, I'm afraid I missed this. Ever so sorry about that.

I'm working on addressing this now. Having had a quick play I think I like the idea of using a version of the approach suggested in https://github.com/abo-abo/swiper/issues/205#issuecomment-134571578 by @abo-abo. I'm going to rework `boxquote-describe-function` and `boxquote-describe-variable` accordingly. (although knowing if the changes I make will still work in XEmacs will be a little more tricky as I don't really have access to that any more and have no simple means of testing it right now -- my focus is really on GNU Emacs now).

**Comment by davep** [comment]
I believe that [v2.0](https://github.com/davep/boxquote.el/releases/tag/v2.0) should address this. Do let me know if it turns out it doesn't.

**Comment by tsdh** [comment]
Thanks!

**Comment by davep** [comment]
My pleasure. Like I say, if it doesn't quite solve the issue please don't hesitate to let me know. (I should probably set up the package that it was having the issue with so I can test it; and check out the package).
